import json

data = None
with open('india-2015-sub.geojson', 'r') as fin:
    data = json.load(fin)

def change_district(x, y, state):
    for feature in data['features']:
        if feature['properties']['name_2'] == x and feature['properties']['name_1'] == state:
            print(feature['properties']['name_3'], feature['properties']['name_2'], feature['properties']['name_1'],
                '->', feature['properties']['name_3'], y, feature['properties']['name_1'])
            if input() == 'y':
                feature['properties']['name_2'] = y
    return data


def modify(x, y, state, district=None):
    for feature in data['features']:
        if feature['properties']['name_1'] == state and x in feature['properties']['name_3']:
            print(feature['properties']['name_3'], feature['properties']['name_2'], feature['properties']['name_1'],
                '->', y, district or feature['properties']['name_2'], feature['properties']['name_1'])
            if input() == 'y':
                if district:
                    feature['properties']['name_2'] = district
                feature['properties']['name_3'] = y
    return data

# data = modify('Shri Madhopur', 'Sri Madhopur', 'Rajasthan')
# data = modify('379', 'Shahpura', 'Rajasthan')
# data = modify('Nim ka Thana', 'Neem-Ka-Thana', 'Rajasthan')
# data = modify('Dungargarh', 'Sridungargarh', 'Rajasthan', 'Bikaner')
# data = modify('230', 'Gharsana', 'Rajasthan')
# data = modify('211', 'Rawatsar', 'Rajasthan')
# data = modify('Bahror', 'Behror', 'Rajasthan')
# data = modify('Thana Gazi', 'Thanagazi', 'Rajasthan')
# data = modify('Mahwah', 'Mahwa', 'Rajasthan')
# data = modify('Toda Bhim', 'Todabhim', 'Rajasthan')
# data = modify('Nandauti', 'Nandoti', 'Rajasthan')
# data = modify('Sakrai', 'Sikrai', 'Rajasthan')
# data = modify('Nandoti', 'Nadoti', 'Rajasthan')
# data = modify('Dudu', 'Mauzamabad', 'Rajasthan')
# data = modify('Bonali', 'Bonli', 'Rajasthan')
# data = modify('Toda Raisingh', 'Todaraisingh', 'Rajasthan')
# data = modify('Devli', 'Deoli', 'Rajasthan')
# data = modify('Naenwa', 'Nainwa', 'Rajasthan')
# data = modify('Pipalda Kalan', 'Pipalda', 'Rajasthan')
# data = modify('Keshorai Patan', 'Keshoraipatan', 'Rajasthan')
# data = modify('Kota', 'Ladpura', 'Rajasthan')
# data = modify('566', 'Bhinay', 'Rajasthan')
# data = modify('Gulabpura', 'Hurda', 'Rajasthan')
# data = modify('Devgarh', 'Deogarh', 'Rajasthan')
# data = modify('617', 'Beawar', 'Rajasthan')
# data = modify('Relmagra', 'Railmagra', 'Rajasthan')
# data = modify('Gangapur', 'Sahara', 'Rajasthan')
# data = modify('Chhipa Barod', 'Chhipabarod', 'Rajasthan')
# data = modify('Jhalarapatan', 'Jhalrapatan', 'Rajasthan')
# data = modify('Arnaud', 'Arnod', 'Rajasthan')
# data = modify('Ghatol', 'Peepalkhoont', 'Rajasthan')
# data = modify('Kalinjara', 'Kushalgarh', 'Rajasthan')
# data = modify('965', 'Bagidora', 'Rajasthan')
# data = modify('748', 'Chittaurgarh', 'Rajasthan')
# data = modify('Nakhtarana', 'Nakhatrana', 'Gujarat')
# data = modify('Naliya', 'Abdasa', 'Gujarat')
# data = modify('Disa', 'Deesa', 'Gujarat')
# data = modify('Diyodar', 'Deodar', 'Gujarat')
# data = modify('Siddhapur', 'Sidhpur', 'Gujarat')
# data = modify('Chanasma', 'Becharaji', 'Gujarat')
# data = modify('922', 'Chanasma', 'Gujarat')
# data = modify('Maliya Miyana', 'Maliya', 'Gujarat')
# data = modify('Morbi', 'Morvi', 'Gujarat', 'Rajkot')
# data = modify('Wankaner', 'Wankaner', 'Gujarat', 'Rajkot')
# data = modify('Dwarka', 'Okhamandal', 'Gujarat', 'Dwarka')
# data = modify('Kalyanpur', 'Kalyanpur', 'Gujarat', 'Dwarka')
# data = modify('Bhanvad', 'Bhanvad', 'Gujarat', 'Dwarka')
# data = modify('Jam Jodhpur', 'Jamjodhpur', 'Gujarat')
# data = modify('Maliya', 'Maliya', 'Gujarat', 'Morvi')
# data = modify('Maliya', 'Malia', 'Gujarat', 'Junagadh')
# data = modify('Halvad', 'Halvad', 'Gujarat', 'Surendranagar')
# data = modify('Okhamandal', 'Okhamandal', 'Gujarat', 'Jamnagar')
# data = modify('Kalyanpur', 'Kalyanpur', 'Gujarat', 'Jamnagar')
# data = modify('Bhanvad', 'Bhanvad', 'Gujarat', 'Jamnagar')
# data = modify('Kodinar', 'Kodinar', 'Gujarat', 'Junagadh')
# data = modify('Veraval', 'Patan-Veraval', 'Gujarat', 'Junagadh')
# data = modify('Khambaliya', 'Khambhalia', 'Gujarat', 'Jamnagar')
# data = modify('Vanthli', 'Vanthali', 'Gujarat', 'Jamnagar')
# data = modify('Talala', 'Talala', 'Gujarat', 'Junagadh')
# data = modify('Jafarabad', 'Jafrabad', 'Gujarat')
# data = modify('Kundla', 'Savar Kundla', 'Gujarat')
# data = modify('Gariyadhar', 'Gariadhar', 'Gujarat')
# data = modify('Gadhada', 'Gadhada', 'Gujarat', 'Bhavnagar')
# data = modify('Valabhipur', 'Vallabhipur', 'Gujarat', 'Bhavnagar')
# data = modify('Maliya', 'Maliya', 'Gujarat', 'Rajkot')
# data = modify('Khambhaliya', 'Khambhalia', 'Gujarat', 'Jamnagar')
# data = modify('Vanthali', 'Vanthali', 'Gujarat', 'Junagadh')
# data = modify('Vadia', 'Kunkavav Vadia', 'Gujarat')
# data = modify('1182', 'Gondal', 'Gujarat')
# data = modify('Jam Kandorna', 'Jamkandorna', 'Gujarat')
# data = modify('1171', 'Kotda Sangani', 'Gujarat')
# data = modify('Lodhi ka Mahal', 'Lodhika', 'Gujarat')
# data = modify('Padadhari', 'Paddhari', 'Gujarat')
# data = modify('1232', 'Ghogha', 'Gujarat')
# data = modify('Botad', 'Botad', 'Gujarat', 'Botad')
# data = modify('Hansot Mahal', 'Hansot', 'Gujarat')
# data = modify('Umargam', 'Umbergaon', 'Gujarat')
# data = modify('Ahwa', 'The Dangs', 'Gujarat')
# data = modify('Vansada', 'Bansda', 'Gujarat')
# data = modify('Nijhar', 'Nizar', 'Gujarat')
# data = modify('Rajpipla', 'Nandod', 'Gujarat')
# data = change_district('Chhota Udaipur', 'Vadodara')
# data = change_district('Dahod', 'Dohad')
# data = modify('Botad', 'Botad', 'Gujarat', 'Bhavnagar')
# data = modify('Tilakwada', 'Tilakwada', 'Gujarat', 'Narmada')
# data = modify('Naswadi', 'Nasvadi', 'Gujarat')
# data = modify('Devgadh Baria', 'Devgadbaria', 'Gujarat')
# data = change_district('Mahisagar', 'Panch Mahals', 'Gujarat')
# data = change_district('Aravalli', 'Sabar Kantha', 'Gujarat')
# data = modify('Lunavada', 'Lunawada', 'Gujarat')
# data = modify('Vadasinor', 'Balasinor', 'Gujarat')
# data = modify('Dahegam', 'Dehgam', 'Gujarat')
# data = modify('Mahemdavad', 'Mehmedabad', 'Gujarat')
# data = modify('Ahmadabad', 'Ahmadabad City', 'Gujarat')
# data = modify('Waghoriya', 'Vaghodia', 'Gujarat')
# data = modify('Devgadh Bariya', 'Devgadbaria', 'Gujarat')
# data = modify('Dohad', 'Dahod', 'Gujarat')
# data = modify('Ankleshwar', 'Anklesvar', 'Gujarat')
# data = modify('Vijayanagar', 'Vijaynagar', 'Gujarat')
# data = modify('Khed Brahma', 'Khedbrahma', 'Gujarat')
# data = modify('1344', 'Chorasi', 'Gujarat')
# data = modify('1327', 'Chorasi', 'Gujarat')
# data = modify('Dahod', 'Dohad', 'Gujarat')
# data = modify('Pathankot', 'Pathankot', 'Punjab', 'Gurdaspur')
# data = modify('Jalandhar', 'Jalandhar - I', 'Punjab')
# data = modify('Nawashahr', 'Nawanshahr', 'Punjab')
# data = modify('Ludhiana', 'Ludhiana (East)', 'Punjab')
# data = modify('Maler Kotla', 'Malerkotla', 'Punjab')
# data = change_district('Fazilka', 'Firozpur', 'Punjab')
# data = modify('Rupnagar', 'Rup Nagar', 'Punjab')
# data = modify('Rajpura', 'Dera Bassi', 'Punjab')
# data = modify('Narayangarh', 'Naraingarh', 'Haryana')
# data = modify('Gulha', 'Guhla', 'Haryana')
# data = modify('Asandh', 'Assandh', 'Haryana')
# data = modify('Kosli', 'Kosli', 'Haryana', 'Rewari')
# data = modify('Firozpur Jhirka', 'Ferozepur Jhirka', 'Haryana')
# data = modify('Hathin', 'Hathin', 'Haryana', 'Palwal')
# data = modify('155', 'Patiala', 'Punjab')
data = modify('Kyelang', 'Lahul', 'Himachal Pradesh')
data = modify('Dharmshala', 'Dharmsala', 'Himachal Pradesh')
data = modify('42', 'Jaswan', 'Himachal Pradesh')

 
    
with open('india-2015-sub.geojson', 'w') as fout:
    json.dump(data, fout)